version: '3'

services:

  db:
    image: mattermost/mattermost-prod-db:5.17.1
    read_only: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - ${BASE_PATH:-/data}/postgresql:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

  app:
    image: mattermost/mattermost-prod-app:5.17.1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - ${BASE_PATH:-/data}/config:/mattermost/config:rw
      - ${BASE_PATH:-/data}/data:/mattermost/data:rw
      - ${BASE_PATH:-/data}/logs:/mattermost/logs:rw
      - ${BASE_PATH:-/data}/plugins:/mattermost/plugins:rw
      - ${BASE_PATH:-/data}/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

  web:
    image: mattermost/mattermost-prod-web:5.17.1
    read_only: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    labels:
      - traefik.http.routers.mattermost.entrypoints=https
      - traefik.http.routers.mattermost.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-route53}
      - traefik.http.routers.mattermost.tls=true
      - traefik.http.routers.mattermost.rule=${SITE_URL:-Host(`chat.infra.naturalis.nl`)}
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ${BASE_PATH:-/data}/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    # environment:
    #  - MATTERMOST_ENABLE_SSL=true
    env_file:
      - .env

  traefik:
    image: traefik:2.1
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - web
      - default
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik

networks:
    default:
    web:
        external: true
