[Global]
  checkNewVersion = true
  sendAnonymousUsage = false

[log]
  level = "INFO"

[entrypoints]
  [entrypoints.http]
  address = ":80"

  [entrypoints.https]
  address = ":443"

[api]
  dashboard = true
  debug = false
  insecure = true

[http.routers]
  [http.routers.router0]
  entrypoints = ["http"]
  rule = "HostRegexp(`{any:.*}`)"
  middlewares = ["https-redirect"]
  service = "dummy"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedbydefault = false
  [providers.file]
    filename = "dynamic-conf.toml"
